### ISSUE TITLE
Produces invalid YAML

### ISSUE THREAD

**Issue by Sebelino** [tarekbecker/vim-yaml-formatter#3]
With `let g:yaml_formatter_indent_collection=1`, running `:YAMLFormat` on the following file:

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
```

produces:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace

```

which cannot even be parsed. Expected:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
```
